//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors
    {
        public int IdDoctor { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public int Role { get; set; }
        public string Login { get; set; }
        public int Gender { get; set; }
        public Nullable<int> Departament { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Users Users { get; set; }
        public virtual Genders Genders { get; set; }
        public virtual HospitalDepartments HospitalDepartments { get; set; }
    }
}
